--Tao quyen cho Quanly
CREATE ROLE Quanly

--Cấp quyền các bảng cho Quản lý
GRANT SELECT, INSERT, DELETE, UPDATE ON ThuThu TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON CuonSach TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON DangKy TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON DauSach TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON DocGia TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON KhuVucSach TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON Muon TO Quanly
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON QuaTrinhMuon TO Quanly
GO

--CAP QUYEN CAC STORE PROCEDURE CHO QUAN LY
GRANT EXEC, ALTER ON Proc_Cho_Muon_sach TO QuanLy
GRANT EXEC, ALTER ON Proc_tra_sach TO QuanLy
GRANT EXEC, ALTER ON PROC_DANH_SACH_QUA_HAN TO QuanLy
GRANT EXEC, ALTER ON PROC_DANH_SACH_TOI_HAN_TRA TO QuanLy
GRANT EXEC, ALTER ON PROC_DANH_SACH_DA_MUON TO QuanLy
GRANT EXEC, ALTER ON PROC_DANH_SACH_DA_TRA TO QuanLy
GRANT EXEC, ALTER ON PROC_SO_SACH_DA_MUON TO QuanLy
GRANT EXEC, ALTER ON PROC_SO_SACH_MUON TO QuanLy
GRANT EXEC, ALTER ON PROC_THU_THU_TRUC TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_ThuThu TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_ThuThu TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_ThuThu TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_KhuVucSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_KhuVucSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_KhuVucSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_DangKy TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_DangKy TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_DangKy TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_Muon TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_Muon TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_Muon TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_DocGia TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_DocGia TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_DocGia TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_DauSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_DauSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_DauSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Sua_CuonSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Them_CuonSach TO QuanLy
GRANT EXEC, ALTER ON Proc_Xoa_CuonSach TO QuanLy

--CAP QUYEN CAC FUNCTION CHO QUAN LY
GRANT SELECT, ALTER ON Func_tinh_tien_den TO QuanLy	
GRANT SELECT, ALTER ON Func_DangKy_BangSTTDangKy TO QuanLy
GRANT SELECT, ALTER ON Func_Check_KNIDTT TO QuanLy
GRANT SELECT, ALTER ON Func_Check_KNMaDocGia TO QuanLy
GRANT SELECT, ALTER ON Func_Check_MaKhuVucSach TO QuanLy
GRANT SELECT, ALTER ON Func_Check_KNMaSachTenNXB TO QuanLy
GRANT SELECT, ALTER ON Func_Check_KNMaCuon TO QuanLy
GRANT SELECT, ALTER ON Func_Check_DauSach TO QuanLy
GRANT SELECT, ALTER ON Func_Check_KhuVuc TO QuanLy
GRANT SELECT, ALTER ON Func_Check_NXB TO QuanLy

--Tao quyen cho Thuthu
CREATE ROLE Nhanvien

--Cấp quyền các bảng cho Nhân viên( Thủ thư)
GRANT SELECT, INSERT, DELETE, UPDATE ON DangKy TO Nhanvien
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON DocGia TO Nhanvien
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON Muon TO Nhanvien
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON QuaTrinhMuon TO Nhanvien
GO

--CAP QUYEN CAC STORE PROCEDURE CHO THU THU
GRANT EXEC, ALTER ON Proc_Cho_Muon_sach TO Nhanvien
GRANT EXEC, ALTER ON Proc_tra_sach TO Nhanvien
GRANT EXEC, ALTER ON PROC_DANH_SACH_QUA_HAN TO Nhanvien
GRANT EXEC, ALTER ON PROC_DANH_SACH_TOI_HAN_TRA TO Nhanvien
GRANT EXEC, ALTER ON PROC_DANH_SACH_DA_MUON TO Nhanvien
GRANT EXEC, ALTER ON PROC_DANH_SACH_DA_TRA TO Nhanvien
GRANT EXEC, ALTER ON PROC_SO_SACH_DA_MUON TO Nhanvien
GRANT EXEC, ALTER ON PROC_SO_SACH_MUON TO Nhanvien
GRANT EXEC, ALTER ON Proc_Them_DangKy TO Nhanvien
GRANT EXEC, ALTER ON Proc_Sua_DangKy TO Nhanvien
GRANT EXEC, ALTER ON Proc_Xoa_DangKy TO Nhanvien
GRANT EXEC, ALTER ON Proc_Them_Muon TO Nhanvien
GRANT EXEC, ALTER ON Proc_Sua_Muon TO Nhanvien
GRANT EXEC, ALTER ON Proc_Xoa_Muon TO Nhanvien
GRANT EXEC, ALTER ON Proc_Them_DocGia TO Nhanvien
GRANT EXEC, ALTER ON Proc_Sua_DocGia TO Nhanvien
GRANT EXEC, ALTER ON Proc_Xoa_DocGia TO Nhanvien

--CAP QUYEN CAC FUNCTION CHO THU THU
GRANT SELECT, ALTER ON Func_tinh_tien_den TO Nhanvien	
GRANT SELECT, ALTER ON Func_DangKy_BangSTTDangKy TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_KNMaDocGia TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_MaKhuVucSach TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_KNMaSachTenNXB TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_KNMaCuon TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_DauSach TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_KhuVuc TO Nhanvien
GRANT SELECT, ALTER ON Func_Check_NXB TO Nhanvien

